modLoader="javafml"
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT License"

[[mods]]
modId="mekanismneutronactivator"
version="1.2.3"
displayName="Mekanism: Neutron Activator"
credits="Thanks for this mod goes to original mod creators"
authors="michanide"
description='''
Mekanism has processing technology which uses neutron.
This technology is necessary for processing radioactive waste and producing D-T fuel.
Currently practical method uses neutron beams from the sun.
This method has the weakness of being weather and climate dependent.
This weakness can lead to the shutdown of fusion reactors and leakage of radioactive waste.

That is the reason why we developed a new method.
This new method uses a fusion reaction as a neutron source.
This method is weather and climate independent and can overcome the weaknesses of current methods.

PS: We developed another method which uses nuclear waste. This is for the environments where the sun is unavailable.
'''

[[dependencies.mekanismneutronactivator]]
    modId="forge"
    mandatory=true
    versionRange="[40.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mekanismneutronactivator]]
    modId="mekanism"
    mandatory=true
    versionRange="[10.2.5,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.mekanismneutronactivator]]
    modId="mekanismgenerators"
    mandatory=true
    versionRange="[10.2.5,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.mekanismneutronactivator]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mekanism]]
    modId="jei"
    mandatory=false
    versionRange="[9.7.0.180,)"
    ordering="AFTER"
    side="BOTH"