modLoader="javafml" #mandatory

loaderVersion="${loader_version_range}" #mandatory

license="${mod_license}"

[[mods]]
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory

description='''
Mekanism has processing technology which uses neutron.
This technology is necessary for processing radioactive waste and producing D-T fuel.
Currently practical method uses neutron beams from the sun.
This method has the weakness of being weather and climate dependent.
This weakness can lead to the shutdown of fusion reactors and leakage of radioactive waste.
That is the reason why we developed a new method.
This new method uses a fusion reaction as a neutron source.
This method is weather and climate independent and can overcome the weaknesses of current methods.

PS: We developed another method which uses nuclear waste. This is for the environments where the sun is unavailable.
'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]] #optional
    modId="neoforge" #mandatory
    type="required" #mandatory
    versionRange="[${neo_version},)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="mekanism"
    type="required"
    versionRange="${mekanism_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="jei"
    type="optional"
    versionRange="${jei_version_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="emi"
    type="optional"
    versionRange="${emi_version_range}"
    ordering="AFTER"
    side="BOTH"